apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  namespace: odoo
spec:
  storageClassName: standard-rwo # standard-rwo is default - in argo you need to pass it 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
